//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace qingjia_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
            this.Database.Initialize(false);
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Account> T_Account { get; set; }
        public virtual DbSet<T_Batch> T_Batch { get; set; }
        public virtual DbSet<T_Class> T_Class { get; set; }
        public virtual DbSet<T_Deadline> T_Deadline { get; set; }
        public virtual DbSet<T_Holiday> T_Holiday { get; set; }
        public virtual DbSet<T_Info> T_Info { get; set; }
        public virtual DbSet<T_InfoDetail> T_InfoDetail { get; set; }
        public virtual DbSet<T_LeaveIntership> T_LeaveIntership { get; set; }
        public virtual DbSet<T_LeaveList> T_LeaveList { get; set; }
        public virtual DbSet<T_LeaveType> T_LeaveType { get; set; }
        public virtual DbSet<T_Menu> T_Menu { get; set; }
        public virtual DbSet<T_New_LeaveList> T_New_LeaveList { get; set; }
        public virtual DbSet<T_RoleMenu> T_RoleMenu { get; set; }
        public virtual DbSet<T_SendList> T_SendList { get; set; }
        public virtual DbSet<T_Statistic> T_Statistic { get; set; }
        public virtual DbSet<T_Student> T_Student { get; set; }
        public virtual DbSet<T_Teacher> T_Teacher { get; set; }
        public virtual DbSet<T_TeacherLeaveType> T_TeacherLeaveType { get; set; }
        public virtual DbSet<T_Type> T_Type { get; set; }
        public virtual DbSet<T_Vacation> T_Vacation { get; set; }
        public virtual DbSet<T_Role> T_Role { get; set; }
        public virtual DbSet<vw_Class> vw_Class { get; set; }
        public virtual DbSet<vw_ClassBatch> vw_ClassBatch { get; set; }
        public virtual DbSet<vw_Holiday> vw_Holiday { get; set; }
        public virtual DbSet<vw_LeaveIntership> vw_LeaveIntership { get; set; }
        public virtual DbSet<vw_LeaveList> vw_LeaveList { get; set; }
        public virtual DbSet<vw_New_LeaveList> vw_New_LeaveList { get; set; }
        public virtual DbSet<vw_NightNameList> vw_NightNameList { get; set; }
        public virtual DbSet<vw_StudenBatch> vw_StudenBatch { get; set; }
        public virtual DbSet<vw_Student> vw_Student { get; set; }
        public virtual DbSet<vw_TeacherLeaveType> vw_TeacherLeaveType { get; set; }
        public virtual DbSet<T_LoginInfo> T_LoginInfo { get; set; }
    
        public virtual int sp_getNightNameList(string teacherID)
        {
            var teacherIDParameter = teacherID != null ?
                new ObjectParameter("TeacherID", teacherID) :
                new ObjectParameter("TeacherID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getNightNameList", teacherIDParameter);
        }
    }
}
