//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace qingjia_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TeacherLeaveType
    {
        public int ID { get; set; }
        public string TeacherID { get; set; }
        public Nullable<int> LeaveTypeID { get; set; }
        public Nullable<int> EnableMessage { get; set; }
        public Nullable<int> IsDelete { get; set; }
    
        public virtual T_LeaveType T_LeaveType { get; set; }
        public virtual T_Teacher T_Teacher { get; set; }
    }
}
